export const categories = [
  {
    id: 'nouvelle-collection',
    name: 'Nouvelle Collection',
    description: 'Les dernières créations de maroquinerie Maison Zuri.',
    image: '/29.png',
  },
  {
    id: 'sacs-a-main',
    name: 'Sacs à Main',
    description: 'L\'élégance au bout des doigts pour votre quotidien.',
    image: '/28.jpg',
  },
  {
    id: 'pochettes',
    name: 'Pochettes & Soirée',
    description: 'L\'accessoire idéal pour vos moments d\'exception.',
    image: '/17.jpg',
  },
  {
    id: 'sacs-bandouliere',
    name: 'Sacs Bandoulière',
    description: 'Liberté de mouvement et style affirmé.',
    image: '/10.jpg',
  },
  {
    id: 'cabas-voyage',
    name: 'Cabas & Voyage',
    description: 'De l\'espace sans compromis sur le raffinement.',
    image: '/34.jpg',
  },
  {
    id: 'best-sellers',
    name: 'Best-Sellers',
    description: 'Les icônes plébiscitées par notre communauté.',
    image: '/21.jpg',
  },
];

export const products = [
  {
    id: '1',
    name: 'Sac Iconique "Zuri" Noir',
    price: 320000,
    description: 'Le fleuron de notre collection. Un cuir d\'exception pour une allure intemporelle.',
    category: 'best-sellers',
    image: '/29.png',
    gallery: ['/29.png', '/30.jpg'],
  },
  {
    id: '2',
    name: 'Saffiano "Atelier" Camel',
    price: 285000,
    description: 'Structure rigide et finitions dorées pour ce sac à main sophistiqué.',
    category: 'sacs-a-main',
    image: '/28.jpg',
    gallery: ['/28.jpg', '/27.jpg'],
  },
  {
    id: '3',
    name: 'Pochette "Belle de Nuit"',
    price: 95000,
    description: 'Une touche d\'éclat pour vos soirées les plus mémorables.',
    category: 'pochettes',
    image: '/17.jpg',
    gallery: ['/17.jpg'],
  },
  {
    id: '4',
    name: 'Besace "Nomade" Olive',
    price: 175000,
    description: 'Le compagnon parfait pour une journée active tout en restant chic.',
    category: 'sacs-bandouliere',
    image: '/10.jpg',
    gallery: ['/10.jpg'],
  },
  {
    id: '5',
    name: 'Grand Cabas "Horizon"',
    price: 245000,
    description: 'Volume généreux et cuir souple pour vos escapades ou vos journées chargées.',
    category: 'cabas-voyage',
    image: '/34.jpg',
    gallery: ['/34.jpg'],
  },
  {
    id: '6',
    name: 'Sac Seau "Tradition"',
    price: 215000,
    description: 'Un design classique revisité avec la modernité Maison Zuri.',
    category: 'sacs-a-main',
    image: '/21.jpg',
    gallery: ['/21.jpg'],
  },
  {
    id: '7',
    name: 'Mini Sac "Bijou"',
    price: 125000,
    description: 'Petit par la taille, immense par son caractère.',
    category: 'nouvelle-collection',
    image: '/23.jpg',
    gallery: ['/23.jpg'],
  },
  {
    id: '8',
    name: 'Pochette "Enveloppe" Cuir',
    price: 85000,
    description: 'Épure et minimalisme pour cette pochette en cuir grainé.',
    category: 'pochettes',
    image: '/15.jpg',
    gallery: ['/15.jpg'],
  }
];
